// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bedkbeixqoywaxvtxuhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZGtiZWl4cW95d2F4dnR4dWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MDg2MjMsImV4cCI6MjA1MzE4NDYyM30.Fd2cVgyKR1mfYlhxfg0mqfbyeHrtaNbTp7BlxHICuqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);